# Generated by Django 5.0.7 on 2024-07-14 21:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_1', models.CharField(max_length=50)),
                ('player_2', models.CharField(max_length=50)),
                ('overall_1', models.IntegerField(blank=True, default=0, null=True)),
                ('overall_2', models.IntegerField(blank=True, default=0, null=True)),
                ('matchvideo', models.CharField(blank=True, max_length=200, null=True)),
                ('tournament_winner', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('forround', models.ForeignKey(limit_choices_to={'finished': False}, on_delete=django.db.models.deletion.CASCADE, to='round.round')),
            ],
        ),
    ]
